### ISSUE TITLE
div>div instead ul>li 

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-coffeeroasters#5]
![image](https://user-images.githubusercontent.com/79502241/142885896-0779f0b3-3459-4245-9558-694b41875cd9.png)
yuqorida qism ro'yhat shaklidaga o'xshayapti. shuning uchun div>div o'rniga ul>li bergan yaxshi
![image](https://user-images.githubusercontent.com/79502241/142885831-ba008fc8-e965-4171-8b16-d177dab4cb55.png)

**Comment by BekzodLolayev** [comment]
Bajarildi
