### ISSUE TITLE
order is better

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-coffeeroasters#6]
![image](https://user-images.githubusercontent.com/79502241/142886818-42ffad4f-e798-4205-949d-dc9cd2dda55f.png)
rasmlarni yuqoridagi holatda joylashtirish uchun `order` va css selectorlari orqali to'g'rilash yaxshiroq yaxshiroq

siz buni html kodni o'zgartirish orqali(imgni joylashuvini surish orqali) qilyapsiz. Bu qism dinamik bo'lishi mumkin. Agar backenddan ma'lumot kelsa u avtomatik ravishda o'zgaishi kerak.
![image](https://user-images.githubusercontent.com/79502241/142886679-4178c3bf-f1e6-41ef-b664-daecfc1726f9.png)

**Comment by BekzodLolayev** [comment]
background image qilib joylaymi shunda
