### ISSUE TITLE
no line

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [BekzodLolayev/bek-coffeeroasters#9]
Maketda:
![image](https://user-images.githubusercontent.com/79502241/144068872-e176523b-ea1b-40d2-9aab-774467ce93d9.png)
sizda:
![image](https://user-images.githubusercontent.com/79502241/144068932-ad65c06d-01f5-4d54-b966-b513693722e4.png)

**Comment by BekzodLolayev** [comment]
ha buni Muhammadjavohir aka keyin o'rgatyishlarini aytgandi
